//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlinkData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOnStart {
            get {
                return ((bool)(this["ShowOnStart"]));
            }
            set {
                this["ShowOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 400")]
        public global::System.Drawing.Size ShowPubsSize {
            get {
                return ((global::System.Drawing.Size)(this["ShowPubsSize"]));
            }
            set {
                this["ShowPubsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ShowPubsLocation {
            get {
                return ((global::System.Drawing.Point)(this["ShowPubsLocation"]));
            }
            set {
                this["ShowPubsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 400")]
        public global::System.Drawing.Size ShowFestivalsSize {
            get {
                return ((global::System.Drawing.Size)(this["ShowFestivalsSize"]));
            }
            set {
                this["ShowFestivalsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ShowFestivalsLocation {
            get {
                return ((global::System.Drawing.Point)(this["ShowFestivalsLocation"]));
            }
            set {
                this["ShowFestivalsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 400")]
        public global::System.Drawing.Size ShowPeopleSize {
            get {
                return ((global::System.Drawing.Size)(this["ShowPeopleSize"]));
            }
            set {
                this["ShowPeopleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ShowPeopleLocation {
            get {
                return ((global::System.Drawing.Point)(this["ShowPeopleLocation"]));
            }
            set {
                this["ShowPeopleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 400")]
        public global::System.Drawing.Size ShowTownsSize {
            get {
                return ((global::System.Drawing.Size)(this["ShowTownsSize"]));
            }
            set {
                this["ShowTownsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ShowTownsLocation {
            get {
                return ((global::System.Drawing.Point)(this["ShowTownsLocation"]));
            }
            set {
                this["ShowTownsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 400")]
        public global::System.Drawing.Size ShowLinksSize {
            get {
                return ((global::System.Drawing.Size)(this["ShowLinksSize"]));
            }
            set {
                this["ShowLinksSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ShowLinksLocation {
            get {
                return ((global::System.Drawing.Point)(this["ShowLinksLocation"]));
            }
            set {
                this["ShowLinksLocation"] = value;
            }
        }
    }
}
